### ISSUE TITLE
数据存储在哪里呢？

### ISSUE THREAD

**Issue by CodingOctocat** [FerryYoungFan/VirtualCockroach#16]
公司养的蟑螂有感情了，想挪回家养😀

**Comment by FerryYoungFan** [comment]
win10 下的默认储存位置在
C:\Users\<用户名>\AppData\Roaming\com.FanSeline.SoManyRoaches

**Comment by FerryYoungFan** [comment]
win10 下的默认储存位置在
C:\Users\<用户名>\AppData\Roaming\com.FanSeline.VirtualCockroach

**Comment by zyuelei** [comment]
@FerryYoungFan mac呢，mac能和windows互相转数据嘛？
