### ISSUE TITLE
macOS无法喂食?

### ISSUE THREAD

**Issue by TheMasterOfMagic** [FerryYoungFan/VirtualCockroach#5]
今天刚看到这个项目, 马上就下载运行了, 很喜欢!
有个问题就是无法喂食? 一开始的时候就无法喂食, 那会儿还想着是不是饥饿度不够高的原因.
不过这会儿已经这样了, 还是无法喂食  
<img width="317" alt="屏幕快照 2019-09-19 下午9 49 31" src="https://user-images.githubusercontent.com/25054321/65249976-6539b900-db27-11e9-8829-bdb9e6136a6b.png">  
就是左键点击半透明框无反应, 点击半透明框以外的地方就正常聚焦到被点击的窗口去了, 没有出现食物.
mac系统是最新版.

**Comment by FerryYoungFan** [comment]
请试一下一小时前上传的V016 fixed版本。
新系统的API可能对透明度进行了int/floor计算而不是round
我把原本完全透明的按钮改成不完全透明了
不过我暂时没有最新的mac os，不保证不出现其它兼容问题

**Comment by TheMasterOfMagic** [comment]
问题解决👍
